export const nocodeEditorWidgetCapabilityBaseGenerated = {
  version: '2026-05-23',
  widgets: [
    {
      type: 'widget.form.textInput',
      name: '单行文本',
      aliases: ['input', 'text', 'string', 'textinput', 'singleline', 'singlelinetext', 'shorttext', 'email', 'mail', '单行', '单行文本', '文本', '输入框'],
      family: 'text',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.textarea',
      name: '多行文本',
      aliases: ['textarea', 'multiline', 'multilinetext', 'paragraph', 'longtext', '多行', '多行文本', '备注'],
      family: 'text',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.numberInput',
      name: '数字',
      aliases: ['number', 'integer', 'float', '数字'],
      family: 'number',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.amountInput',
      name: '金额',
      aliases: ['amount', 'currency', 'money', '价格', '金额', '单价', '总价'],
      family: 'number',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.serialNumber',
      name: '自动编号',
      aliases: ['serial', 'autoid', '编号', '单号', '流水号'],
      family: 'text',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.datePicker',
      name: '日期',
      aliases: ['date', 'datetime', '日期', '日期时间'],
      family: 'date',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.dateRangePicker',
      name: '日期范围',
      aliases: ['daterange', 'date-range', '日期范围', '时间范围'],
      family: 'date',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.timePicker',
      name: '时间',
      aliases: ['time', 'timepicker', '时间', '时分秒'],
      family: 'date',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.radioGroup',
      name: '单选',
      aliases: ['radio', 'singlechoice', '单选'],
      family: 'enum',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['enumOptions'],
    },
    {
      type: 'widget.form.checkboxGroup',
      name: '多选',
      aliases: ['checkbox', 'multichoice', '多选'],
      family: 'enum',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['enumOptions'],
    },
    {
      type: 'widget.form.treeSelect',
      name: '下拉单选',
      aliases: ['select', 'dropdown', 'treeselect', 'relation', '关联', '来自他表'],
      family: 'relation',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['source'],
    },
    {
      type: 'widget.form.treeMultipleSelect',
      name: '下拉多选',
      aliases: ['multiselect', 'treeMultipleSelect', '下拉多选'],
      family: 'relation',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['source'],
    },
    {
      type: 'widget.form.memberSelect',
      name: '成员',
      aliases: ['member', 'user', '成员', '人员'],
      family: 'organization',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.departmentSelect',
      name: '部门',
      aliases: ['department', 'dept', '部门'],
      family: 'organization',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.subform',
      name: '子表单',
      aliases: ['subform', '子表单', '明细', '清单', '条目'],
      family: 'subform',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['children'],
    },
    {
      type: 'widget.form.phoneInput',
      name: '手机号',
      aliases: ['phone', 'mobile', '手机号', '联系电话'],
      family: 'text',
      planningPriority: 'medium',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.address',
      name: '地址',
      aliases: ['address', '地址', '收货地址', '联系地址'],
      family: 'text',
      planningPriority: 'medium',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.rate',
      name: '评分',
      aliases: ['rate', 'rating', '评分', '打分'],
      family: 'advanced',
      planningPriority: 'medium',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.position',
      name: '定位',
      aliases: ['position', 'location', '定位'],
      family: 'advanced',
      planningPriority: 'medium',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.tagInput',
      name: '标签',
      aliases: ['tag', 'tags', '标签'],
      family: 'advanced',
      planningPriority: 'medium',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.richTextEditor',
      name: '富文本',
      aliases: ['richtext', 'editor', '富文本'],
      family: 'advanced',
      planningPriority: 'medium',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.markdownEditor',
      name: 'Markdown',
      aliases: ['markdownEditor'],
      family: 'advanced',
      planningPriority: 'low',
      promptVisible: false,
      requires: ['none'],
    },
    {
      type: 'widget.form.image-uploader',
      name: '图片上传',
      aliases: ['image', 'imageupload', '图片', '上传图片'],
      family: 'media',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.file-uploader',
      name: '附件上传',
      aliases: ['file', 'attachment', '附件', '上传附件'],
      family: 'media',
      planningPriority: 'high',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.switch',
      name: '开关',
      aliases: ['switch', 'toggle', 'boolean', '开关'],
      family: 'enum',
      planningPriority: 'medium',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.searchForm',
      name: '查询表单',
      aliases: ['searchform', '查询表单'],
      family: 'display',
      planningPriority: 'low',
      promptVisible: false,
      requires: ['none'],
    },
    {
      type: 'widget.form.hyperlink',
      name: '超链接',
      aliases: ['link', 'url', 'hyperlink', '超链接'],
      family: 'display',
      planningPriority: 'low',
      promptVisible: false,
      requires: ['none'],
    },
    {
      type: 'widget.form.autoCompute',
      name: '自动计算',
      aliases: ['autocompute', 'formula', 'calc', '自动计算'],
      family: 'advanced',
      planningPriority: 'medium',
      promptVisible: true,
      requires: ['none'],
    },
    {
      type: 'widget.form.handwrittenSignature',
      name: '手写签名',
      aliases: ['handwrittenSignature', 'signature', '签名', '手写签名'],
      family: 'display',
      planningPriority: 'low',
      promptVisible: false,
      requires: ['none'],
    },
    {
      type: 'widget.form.selectData',
      name: '选择数据',
      aliases: ['selectdata', '选择数据'],
      family: 'display',
      planningPriority: 'low',
      promptVisible: false,
      requires: ['none'],
    },
    {
      type: 'widget.form.relatedData',
      name: '关联数据',
      aliases: ['relateddata', '关联数据'],
      family: 'display',
      planningPriority: 'low',
      promptVisible: false,
      requires: ['none'],
    },
    {
      type: 'widget.form.titleBar',
      name: '标题栏',
      aliases: ['title', 'titlebar', '标题栏'],
      family: 'display',
      planningPriority: 'low',
      promptVisible: false,
      requires: ['none'],
    },
    {
      type: 'widget.form.imageTextShow',
      name: '图文展示',
      aliases: ['imagetext', '图文展示'],
      family: 'display',
      planningPriority: 'low',
      promptVisible: false,
      requires: ['none'],
    },
    {
      type: 'widget.form.multipleTabs',
      name: '选项卡',
      aliases: ['tabs', 'tab', '选项卡'],
      family: 'display',
      planningPriority: 'low',
      promptVisible: false,
      requires: ['none'],
    },
  ],
} as const

export type NocodeEditorWidgetCapabilityBaseGenerated = typeof nocodeEditorWidgetCapabilityBaseGenerated
