export const nocodeEditorWidgetCapabilityOverlay = {
  version: '2026-05-23',
  widgets: [
    {
      type: 'widget.form.textInput',
      useWhen: ['字段用于姓名、简称、标题、编号文本等普通短文本输入', '字段没有明显关系、枚举、日期、金额或附件语义'],
      avoidWhen: ['值本质来自其他表单', '字段语义明显属于金额、日期、附件、子表单'],
      clarificationTriggers: ['字段只有“联系人 / 负责人 / 经办人”等歧义词时不要直接默认它'],
      fallbackTypes: ['widget.form.textInput'],
      examples: ['客户简称', '外部联系人姓名'],
      notes: ['它是默认兜底组件，不代表优先组件。'],
    },
    {
      type: 'widget.form.textarea',
      useWhen: ['字段用于备注、说明、描述、原因', '需要比单行文本更长的输入'],
      avoidWhen: ['结构化明细应改用 subform', '富文本编辑需求应改用 richTextEditor'],
      clarificationTriggers: ['只写“说明”但实际需要图文展示时先澄清'],
      fallbackTypes: ['widget.form.textarea', 'widget.form.textInput'],
      examples: ['处理说明', '问题描述'],
    },
    {
      type: 'widget.form.numberInput',
      useWhen: ['字段是数量、次数、天数、分数等普通数值', '不涉及金额格式'],
      avoidWhen: ['金额、单价、总价等优先用 amountInput', '自动编号优先用 serialNumber'],
      clarificationTriggers: ['值看起来更像金额或自动编号时先改用专用组件'],
      fallbackTypes: ['widget.form.numberInput', 'widget.form.textInput'],
      examples: ['库存数量', '培训课时'],
    },
    {
      type: 'widget.form.amountInput',
      useWhen: ['字段表示金额、单价、总价、应收应付', '需要金额语义和格式'],
      avoidWhen: ['只是普通数量时不要滥用', '自动计算公式优先 autoCompute'],
      clarificationTriggers: ['如果其实是自动计算字段，先澄清是否需要公式'],
      fallbackTypes: ['widget.form.amountInput', 'widget.form.numberInput', 'widget.form.textInput'],
      examples: ['报销金额', '采购总价'],
    },
    {
      type: 'widget.form.serialNumber',
      useWhen: ['字段是自动生成的编号、单号、流水号', '需要系统自动维护标识'],
      avoidWhen: ['身份证号、工号、学号等业务输入值不要误判成自动编号'],
      clarificationTriggers: ['如果字段更像业务编码而不是系统自动生成，先澄清是否手填'],
      fallbackTypes: ['widget.form.serialNumber', 'widget.form.textInput'],
      examples: ['采购单号', '入库流水号'],
    },
    {
      type: 'widget.form.datePicker',
      useWhen: ['字段记录单一日期或日期时间点', '不是时间范围也不是纯时分秒'],
      avoidWhen: ['时间范围优先用 dateRangePicker', '纯时分秒优先用 timePicker'],
      clarificationTriggers: ['字段只写“时间 / 日期”且粒度不清时先澄清'],
      fallbackTypes: ['widget.form.datePicker', 'widget.form.textInput'],
      examples: ['申请日期', '交付日期'],
    },
    {
      type: 'widget.form.dateRangePicker',
      useWhen: ['字段明确表示开始到结束的范围', '上下文包含起止、期间、范围'],
      avoidWhen: ['只是单一日期时不要使用', '只有纯时分秒时改用 timePicker'],
      clarificationTriggers: ['只写“时间”但没说明范围时先澄清'],
      fallbackTypes: ['widget.form.dateRangePicker', 'widget.form.datePicker', 'widget.form.textInput'],
      examples: ['活动时间范围', '合同有效期'],
    },
    {
      type: 'widget.form.timePicker',
      useWhen: ['字段只记录时分秒或营业时间点', '不是日期也不是范围'],
      avoidWhen: ['需要完整日期时改用 datePicker', '需要范围时改用 dateRangePicker'],
      clarificationTriggers: ['字段只写“时间”但无法确认是不是纯时分秒时先澄清'],
      fallbackTypes: ['widget.form.timePicker', 'widget.form.textInput'],
      examples: ['上课时间', '营业时间'],
    },
    {
      type: 'widget.form.radioGroup',
      useWhen: ['固定少量互斥选项', '选项已知且数量不大'],
      avoidWhen: ['来源来自其他表单时优先 treeSelect', '选项不明确时不要硬编码'],
      clarificationTriggers: ['没有给出可选项时先澄清具体选项'],
      fallbackTypes: ['widget.form.radioGroup', 'widget.form.treeSelect', 'widget.form.textInput'],
      examples: ['是否通过', '性别'],
    },
    {
      type: 'widget.form.checkboxGroup',
      useWhen: ['固定少量可多选的选项集合', '标签、范围、角色等选项已明确给出'],
      avoidWhen: ['需要复用主数据来源时优先 treeMultipleSelect', '选项不明确时不要先造默认值'],
      clarificationTriggers: ['没有明确选项时先澄清 source 或业务选项'],
      fallbackTypes: ['widget.form.checkboxGroup', 'widget.form.treeMultipleSelect', 'widget.form.treeSelect', 'widget.form.textInput'],
      examples: ['适用范围', '参与角色'],
    },
    {
      type: 'widget.form.treeSelect',
      useWhen: ['值本质来自其他表单或主数据', '字段是客户、供应商、项目、仓库、课程、合同等实体'],
      avoidWhen: ['只是手填文本时不要滥用', 'source 不明确时不要静默生成空关系字段'],
      clarificationTriggers: ['没有 source.formName / source.fieldName 时先澄清来源'],
      fallbackTypes: ['widget.form.treeSelect', 'widget.form.radioGroup', 'widget.form.textInput'],
      examples: ['客户', '供应商'],
    },
    {
      type: 'widget.form.treeMultipleSelect',
      useWhen: ['字段是可多选的主数据集合', '标签、技能、角色等需要复用来源表'],
      avoidWhen: ['固定少量选项更适合 checkboxGroup', '来源不明时不要默认生成'],
      clarificationTriggers: ['没有 source 时先澄清是否来自他表还是固定多选项'],
      fallbackTypes: ['widget.form.treeMultipleSelect', 'widget.form.checkboxGroup', 'widget.form.treeSelect', 'widget.form.textInput'],
      examples: ['参与角色', '覆盖区域'],
    },
    {
      type: 'widget.form.memberSelect',
      useWhen: ['申请人、提交人、审批人、处理人等组织内成员身份字段', '需要选择组织成员'],
      avoidWhen: ['外部联系人姓名不要误判为成员', '关系档案中的负责人如果不是组织成员需先澄清'],
      clarificationTriggers: ['负责人、联系人、经办人等歧义字段且上下文不足时先澄清'],
      fallbackTypes: ['widget.form.memberSelect', 'widget.form.treeSelect', 'widget.form.textInput'],
      examples: ['申请人', '审批人'],
    },
    {
      type: 'widget.form.departmentSelect',
      useWhen: ['申请部门、归属部门、审批部门等组织部门字段', '需要选择部门而不是成员'],
      avoidWhen: ['部门负责人这类复合语义先澄清', '如果其实是部门对应成员不要直接选它'],
      clarificationTriggers: ['字段可能在“部门”和“部门负责人”之间摇摆时先澄清'],
      fallbackTypes: ['widget.form.departmentSelect', 'widget.form.treeSelect', 'widget.form.textInput'],
      examples: ['申请部门', '归属部门'],
    },
    {
      type: 'widget.form.subform',
      useWhen: ['字段需要多行结构化明细', '同一表单内要重复记录多条子项'],
      avoidWhen: ['只是长文本描述不要误用', '只有一个值时不用 subform'],
      clarificationTriggers: ['未给 children 时先澄清明细字段结构'],
      fallbackTypes: ['widget.form.subform', 'widget.form.textInput'],
      examples: ['商品明细', '费用条目'],
    },
    {
      type: 'widget.form.image-uploader',
      useWhen: ['字段明确是现场照片、头像、截图、封面等图片证据', '需要上传图片而不是通用文件'],
      avoidWhen: ['只是泛化“附件”时先澄清', '合同、材料类文件更适合 file-uploader'],
      clarificationTriggers: ['字段只写附件时先澄清是否是图片'],
      fallbackTypes: ['widget.form.image-uploader', 'widget.form.file-uploader', 'widget.form.textInput'],
      examples: ['现场照片', '头像'],
    },
    {
      type: 'widget.form.file-uploader',
      useWhen: ['字段明确是合同附件、报销凭证、证明材料等通用文件', '不是纯图片场景'],
      avoidWhen: ['图片证据优先 image-uploader', '字段只写附件但未说明时先澄清'],
      clarificationTriggers: ['字段只写附件时先澄清图片还是文件'],
      fallbackTypes: ['widget.form.file-uploader', 'widget.form.textInput'],
      examples: ['合同附件', '报销凭证'],
    },
    {
      type: 'widget.form.phoneInput',
      useWhen: ['字段明确是手机号、联系电话、手机号段', '需要更明确的电话输入语义'],
      avoidWhen: ['只是联系人姓名不要误用', '如果其实是成员选择字段不要退回电话'],
      clarificationTriggers: ['字段既像电话又像身份标识时先看描述'],
      fallbackTypes: ['widget.form.phoneInput', 'widget.form.textInput'],
      examples: ['联系电话', '手机号码'],
    },
    {
      type: 'widget.form.address',
      useWhen: ['字段明确表示联系地址、收货地址、发货地址', '比普通文本更贴近地址输入'],
      avoidWhen: ['坐标定位优先 position', '普通备注不要误用'],
      clarificationTriggers: ['如果更像地理定位而不是文字地址时先澄清'],
      fallbackTypes: ['widget.form.address', 'widget.form.textarea', 'widget.form.textInput'],
      examples: ['联系地址', '收货地址'],
    },
    {
      type: 'widget.form.switch',
      useWhen: ['字段是是否启用、是否默认、是否公开等布尔状态', '更适合用开关表达 than 固定选项文案'],
      avoidWhen: ['若必须显式展示“是 / 否”“通过 / 不通过”可改用 radioGroup'],
      clarificationTriggers: ['字段虽然是布尔，但业务要求必须显示枚举文案时先看上下文'],
      fallbackTypes: ['widget.form.switch', 'widget.form.radioGroup', 'widget.form.textInput'],
      examples: ['是否启用', '是否默认'],
    },
    {
      type: 'widget.form.richTextEditor',
      useWhen: ['字段需要图文混排的长内容输入', '比普通多行文本有更丰富格式需求'],
      avoidWhen: ['只是简单备注说明时优先 textarea', '展示型图文不默认用于采集'],
      clarificationTriggers: ['如果只是展示内容而非采集字段，先确认是否真的需要输入组件'],
      fallbackTypes: ['widget.form.richTextEditor', 'widget.form.textarea', 'widget.form.textInput'],
      examples: ['活动介绍', '详细说明'],
    },
    {
      type: 'widget.form.tagInput',
      useWhen: ['字段是自由输入标签集合', '不依赖固定枚举或主数据'],
      avoidWhen: ['固定多选更适合 checkboxGroup', '可复用来源表更适合 treeMultipleSelect'],
      clarificationTriggers: ['如果标签集合其实来自固定范围，先澄清是否枚举或 relation'],
      fallbackTypes: ['widget.form.tagInput', 'widget.form.textInput'],
      examples: ['关键标签', '兴趣标签'],
    },
    {
      type: 'widget.form.position',
      useWhen: ['字段明确需要地理定位或位置信息', '不是普通文字地址'],
      avoidWhen: ['纯文本地址优先 address', '普通说明不要误用'],
      clarificationTriggers: ['上下文只写地址、位置但无法判断是坐标还是文本时先澄清'],
      fallbackTypes: ['widget.form.position', 'widget.form.address', 'widget.form.textInput'],
      examples: ['定位位置', '签到地点'],
    },
    {
      type: 'widget.form.rate',
      useWhen: ['字段明确是评分、满意度、打星等分级输入', '比普通数字更有评分语义'],
      avoidWhen: ['普通数量不要误用', '复杂指标计算优先 numberInput / autoCompute'],
      clarificationTriggers: ['如果评分值需要固定选项解释，先看是否更适合 radioGroup'],
      fallbackTypes: ['widget.form.rate', 'widget.form.numberInput', 'widget.form.textInput'],
      examples: ['满意度评分', '服务评分'],
    },
    {
      type: 'widget.form.autoCompute',
      useWhen: ['字段本质是系统公式计算结果', '不应由用户手工录入'],
      avoidWhen: ['普通金额输入不要误用', '第一阶段不把复杂公式细节暴露给模型'],
      clarificationTriggers: ['如果模型无法确认是否为公式字段，先不要强推它'],
      fallbackTypes: ['widget.form.autoCompute', 'widget.form.numberInput', 'widget.form.textInput'],
      examples: ['应收金额', '合计金额'],
    },
    {
      type: 'widget.form.hyperlink',
      useWhen: ['只有在明确需要录入或展示链接地址时再考虑'],
      avoidWhen: ['默认数据采集字段不要优先使用它'],
      clarificationTriggers: ['如果只是普通文本，不要误判成链接字段'],
      fallbackTypes: ['widget.form.hyperlink', 'widget.form.textInput'],
      examples: ['官网链接'],
    },
    {
      type: 'widget.form.handwrittenSignature',
      useWhen: ['只有在明确需要签名采集时再考虑'],
      avoidWhen: ['默认数据采集字段不要优先使用它'],
      clarificationTriggers: ['如果只是上传签字照片或附件，先区分是否真的是签名组件'],
      fallbackTypes: ['widget.form.handwrittenSignature', 'widget.form.image-uploader', 'widget.form.file-uploader', 'widget.form.textInput'],
      examples: ['客户签名'],
    },
    {
      type: 'widget.form.selectData',
      useWhen: ['只有在非常明确需要该低频组件时再考虑'],
      avoidWhen: ['默认数据采集字段不优先使用', '关系选择优先 treeSelect / treeMultipleSelect'],
      clarificationTriggers: ['如果没有强需求，不要先规划它'],
      fallbackTypes: ['widget.form.selectData', 'widget.form.treeSelect', 'widget.form.textInput'],
      examples: ['低频展示型关联选择'],
    },
    {
      type: 'widget.form.relatedData',
      useWhen: ['只有在明确知道是关联数据展示时再考虑'],
      avoidWhen: ['默认数据采集字段不优先使用'],
      clarificationTriggers: ['若用户未明确要求展示型关联组件，不要先规划它'],
      fallbackTypes: ['widget.form.relatedData', 'widget.form.treeSelect', 'widget.form.textInput'],
      examples: ['关联数据显示'],
    },
    {
      type: 'widget.form.searchForm',
      useWhen: ['只有在明确搭建查询界面而非录入表单时才考虑'],
      avoidWhen: ['普通业务录入表单不要默认使用'],
      clarificationTriggers: ['场景如果仍是数据采集，先不要规划它'],
      fallbackTypes: ['widget.form.searchForm', 'widget.form.treeSelect', 'widget.form.textInput'],
      examples: ['高级查询条件区'],
    },
    {
      type: 'widget.form.titleBar',
      useWhen: ['只有用户明确要求布局展示组件时再考虑'],
      avoidWhen: ['默认数据采集字段不要使用标题栏占位'],
      clarificationTriggers: ['如果用户只是说分组，不要先改用布局组件'],
      fallbackTypes: ['widget.form.titleBar', 'widget.form.textInput'],
      examples: ['表单分区标题'],
    },
    {
      type: 'widget.form.imageTextShow',
      useWhen: ['只有用户明确需要展示型图文区域时再考虑'],
      avoidWhen: ['默认数据采集字段不要规划成展示组件'],
      clarificationTriggers: ['如果场景仍然是用户输入，不要先规划图文展示'],
      fallbackTypes: ['widget.form.imageTextShow', 'widget.form.richTextEditor', 'widget.form.textarea', 'widget.form.textInput'],
      examples: ['展示型图文说明区'],
    },
    {
      type: 'widget.form.multipleTabs',
      useWhen: ['只有明确要求复杂布局容器时再考虑'],
      avoidWhen: ['默认数据采集字段不要先规划成布局容器'],
      clarificationTriggers: ['如果只是字段分组，不要先改成 tabs'],
      fallbackTypes: ['widget.form.multipleTabs', 'widget.form.titleBar', 'widget.form.textInput'],
      examples: ['复杂布局容器'],
    },
    {
      type: 'widget.form.markdownEditor',
      useWhen: [],
      avoidWhen: [],
      clarificationTriggers: [],
      fallbackTypes: ['widget.form.textInput'],
    },
  ],
} as const

export type NocodeEditorWidgetCapabilityOverlay = typeof nocodeEditorWidgetCapabilityOverlay
