<template>
  <b2-form-element>
    <el-input v-if="!widget.isReadonly && widget.isEditMode"
      :class="{'mobile': isMobile()}"
      size="default"
      v-model="widget.inputValue"
      :placeholder="widget.placeholder"
    />
    <div
      class="value"
      :class="{'mobile': isMobile()}"
      v-else
      :style="{ color: widget.inputValue ? 'unset' : 'var(--text-color-inactive)' }"
      :title="widget.inputValue || $t('noContent')"
    >
      {{ widget.inputValue || $t('autoGenerated') }}
    </div>
  </b2-form-element>
</template>

<script lang="ts" setup>
import { isMobile } from "@renderer/utils/pure";
import { useWidget } from "@renderer/b2/types";
import { SerialNumber } from "./serialNumber";
import i18next, { $t } from "@renderer/widgets/i18next";

const widget = useWidget<SerialNumber>();

</script>

<style lang="scss" scoped>
.el-input {
  --el-input-border-radius: 4px;
}
.value {
  display: flex;
  height: 32px;
  align-items: center;
  background: var(--el-bg-color-overlay);
  color: var(--el-text-color-primary);
  border: 1px solid var(--border-color);
  border-radius: 2px;
  padding: 0 8px;
  line-height: 20px;
}
.value.mobile {
  height: 40px;
  border-radius: 4px;
  padding: 0 12px !important;
  line-height: 40px;
}
:deep(.el-input-number.mobile) {
  .el-input__wrapper {
    border-radius: 4px;
    background-color: #fff;
    height: 40px;
    padding: 0 12px;
  }
}
</style>
